### ISSUE TITLE
3ds Max 2017 Vray version missing?

### ISSUE THREAD

**Issue by embeh** [zicher3d-org/domemaster-stereo-shader#11]
Looks like the last compiled Vray version is for 3ds Max 2015?

**Comment by AndrewHazelden** [comment]
Hi embeh.

Thanks for your message. I have been meaning to compile a newer set of the 3DS Max/Vray Domemaster3D lens shaders that work with Vray 3.5 but things have been busy at work. Hopefully this new shader compiling task will get done in the next two weeks or so.

 In the mean time created a new Wiki topic [Vray for Max Domemaster3D Shader Compiling](https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Vray-for-Max-Domemaster3D-Shader-Compiling) that has all the details rendering TDs need to know to compile their own custom builds of the lens shaders that match their current 3DS Max + Vray version.

**Comment by embeh** [comment]
Thank you very much for the detailed instructions!
Upon first inspection of the wiki article, I wonder about the version of Visual Studio referenced in it.
3ds Max 2017 [requires](http://help.autodesk.com/view/3DSMAX/2017/ENU/?guid=__files_GUID_6E179A56_5552_4D0B_BA61_BBD37B9E52DB_htm) Visual Studio 2015, 3ds Max 2016 and 2015 require Visual Studio 2012

**Comment by AndrewHazelden** [comment]
The Visual Studio "requirements" for each 3DS Max release is actually quite flexible. Usually that just means that the 3DS Max installer has already installed the required VisualC++ Redistributable package for that specific Visual Studio release version on the end user's system.

If you look in the Domemaster3D legacy shaders folder here on GitHub you can see I was able to compile a version of the lens shaders for Max 2013-2016 + Vray:

[https://github.com/zicher3d-org/domemaster-stereo-shader/tree/master/vray/install/3dsmax/vray%20legacy%20builds](https://github.com/zicher3d-org/domemaster-stereo-shader/tree/master/vray/install/3dsmax/vray%20legacy%20builds)

**Comment by embeh** [comment]
Interesting. 
I was [told to never mix the VS versions](http://siomsystems.com/mixing-visual-studio-versions/), as the different CRTs use different memory allocation systems?

**Comment by AndrewHazelden** [comment]
Thanks for the link. 

Most lens shaders are 90% straight c-code wrapped in a very small amount of C++. A lens shader from a programming perspective carries out a very limited set of functions that merely adjust the ray angles and then return the result back to the renderer so I haven't personally witnessed issues **yet** from mixing Visual Studio versions.

I now have the header files and library resources on hand to compile a Vray for 3DS Max 2014-2017 build of the lens shaders so I hope to have those posted online shortly.

**Comment by AndrewHazelden** [comment]
Hi @embeh . I just compiled new V-Ray 3.4 for 3ds Max 2014/2016/2017 versions of the lens shaders and synced them with the GitHub repository. Let me know if they work correctly for you.

You might have to install the [Microsoft Visual C++ Redistributable Package for Visual Studio 2013 x64](https://www.microsoft.com/en-us/download/details.aspx?id=40784) to use the shaders on your system.
