### ISSUE TITLE
LatLong Render image distorted

### ISSUE THREAD

**Issue by shuggar** [zicher3d-org/domemaster-stereo-shader#14]
I cannot seem to figure out, what I am doing wrong.
I attached an image of my render result. This is not what I was expecting, but I cannot find the correct adjustments.

![triangle floor tiles_domemaster](https://cloud.githubusercontent.com/assets/1178286/24478185/2952f6ec-14da-11e7-81a2-80fedfa87e34.jpg)

**Comment by AndrewHazelden** [comment]
Hi @shuggar. What 3D package and renderer are you using?

Is this an Arnold MtoA rendering? If so you will have to activate the "Zenith Mode" option in the current [LatLongStereo lens shader](https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Arnold-MtoA-LatLongStereo) controls and point the camera upwards on the Y axis when doing scene layout and camera framing. 

Clicking on the ArnoldDomemaster3D shelf and the the **LatLong3D** icon takes care of this.
![arnolddomemaster3d shelf](https://cloud.githubusercontent.com/assets/909728/24485496/402b5bce-14db-11e7-80fd-07f30c3fe60a.png)

Also the Arnold version of the Domeamaster3D shaders' lacks an aspect ratio correction mode so you need to render out a true 2:1 aspect ratio image to match the 360&deg;x180&deg; FOV of your rendering. There are several shelf icons like the 2x1K, 4x2k, and 8x4K buttons that have 2:1 aspect ratio resolution presets you can use to adjust the rendered image size for you quickly and easily without having to open the Render Settings window.

**Comment by shuggar** [comment]
@AndrewHazelden thanks for responding so quickly.
this is C4dtoA, I tried every adjustment, but it did not work.
It never occured to me to point the cam straight up. Will try immediately and post results.
Thanks

**Comment by shuggar** [comment]
@AndrewHazelden ok, this is getting somewhere.
Unfortunately I cannot not get it to render as a stereo image.

I would like to have that as a top to bottom stereo pano, right now this is mono.
I tried doubling the aspect ratio to square, but this does not work for me.

Thanks for helping. Great work on this plugin.

**Comment by shuggar** [comment]
![latlong-mono](https://cloud.githubusercontent.com/assets/1178286/24493768/440ad77e-1530-11e7-8a2c-6b6adfa01254.jpg)

**Comment by AndrewHazelden** [comment]
Hi @shuggar. If you want to create a stereo rendering with the LatLongStereo shader in C4DtoA you need to follow this tip in the Wiki for adjusting the "Camera" control to render out a Left and Right camera view:

https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Arnold-C4DtoA-Domemaster3D-Install#developer-note-on-the-beta-shaders-ui

Changing the aspect ratio to square only creates an single rendered monoscopic image at a time using either the left, center, or right camera view that is defined in the lens shader's **Arnold Tag** that is present on the camera. Rendering a 1:1 aspect ratio does not output a combined stereo over/under frame.

If you want to create an Over/Under formatted stereo panoramic rendering automatically then I suggest you look at [Pedro Gomez's VR Camera](http://pedrofe.com/oculus-camera/) lens shader for Arnold.

**Comment by shuggar** [comment]
@AndrewHazelden got it.
It is a longer workflow to stitch the left and right camera together afterwards in photoshop or after effects, but for me the results are much better than using Pedro Gomez' VR Cam.

The image is way better and there is no "under water" effect. The stereo render is crystal clear.

Thanks
