### ISSUE TITLE
FOV camera squeezes image

### ISSUE THREAD

**Issue by viewmasters** [zicher3d-org/domemaster-stereo-shader#15]
I'm trying to render a previz of a 160 degree screen so I can view it 
![test](https://cloud.githubusercontent.com/assets/26870478/24606976/0127c0e6-1870-11e7-9794-89a7bee0bffd.jpg)
on my Oculus dk2.
I'm using the AFL_FOV camera and it looks okay in the viewport but when I render the circles are not round. How can I fix this?

**Comment by viewmasters** [comment]
It works with the latlong camera

**Comment by DoverStudios** [comment]
The domeAFL_FOV lens shader is rendering out an angular fisheye "circular" image. It expects you to have a 1:1 aspect ratio so that would mean you have to set the render resolution to something like 2048x2048, 3072x3072, etc...
