### ISSUE TITLE
Fisheye >180°?

### ISSUE THREAD

**Issue by jumpjack** [zicher3d-org/domemaster-stereo-shader#18]
How can I use this program with images with FOV>180° ?
My camera has a 235° FOV.

**Comment by AndrewHazelden** [comment]
Domemaster3D is a CG rendering lens shader that works with 3DS Max and Maya. You can customize the 3D camera's field of view setting to any FOV value you want by changing the  **FOV Angle** attribute.

![lens-shader-fov](https://user-images.githubusercontent.com/909728/27864668-e2a46f68-6165-11e7-80d4-1270319ea8b1.png)
