### ISSUE TITLE
Double camera (180+180)

### ISSUE THREAD

**Issue by jumpjack** [zicher3d-org/domemaster-stereo-shader#19]
How can I convert a double-fisheye photo to equirectangular? FOV is also >180°.

**Comment by AndrewHazelden** [comment]
Domemaster3D is a collection of panoramic lens shaders that render fisheye and LatLong image projections. If you want to render a 360x180° panoramic image you should use the LatLong Stereo lens shader to render directly to your final image projection.

What renderer are you using? Are you using 3DS Max or Maya?

**Comment by AndrewHazelden** [comment]
If you are working with live action panoramic fisheye imagery and watch to stitch your photos into a final image projection you will likely want to use a dedicated stitching/composition tool like PTGui, Kolor Autopano, Hugin, After Effects + Mettle SkyBox Studio, etc...
