### ISSUE TITLE
GPL license prevents uploading binaries for new renderer versions

### ISSUE THREAD

**Issue by mdjurev** [zicher3d-org/domemaster-stereo-shader#21]
GPL license prevents linking to closed-source libraries, such as V-Ray's libraries,
This means that we can't help with maintaining the binaries whenever a new version of V-Ray is released. 

Please consider using a less restrictive license.

**Comment by AndrewHazelden** [comment]
Hi @mdjurev . Thanks for your message.

I've brought your points up with my co-developer, Rob. We are in the process of discussing open-source license changes that could be made to better address the needs of linking pre-compiled binary lens shaders to closed-source external renderer libraries.

Out of interest, would an MIT or BSD licensed version of Domemaster3D's source code be preferable?

**Comment by mdjurev** [comment]
Hi @AndrewHazelden 

Thank you for looking into this.
We usually work with MIT license, but AFAIK, BSD and Apache would work fine too.
Basically any license that permits linking to our libraries.

**Comment by AndrewHazelden** [comment]
Hi @mdjurev .

The Domemaster3D open-source license terms have been changed to a [BSD license](https://github.com/zicher3d-org/domemaster-stereo-shader/blob/master/LICENSE).

**Comment by mdjurev** [comment]
Thanks guys, awesome!
