### ISSUE TITLE
No Domemaster3D shelf or menu upon installation, missing details in installation instructions

### ISSUE THREAD

**Issue by uberblah** [zicher3d-org/domemaster-stereo-shader#4]
We ran the default Mac installer for Maya 2015, following provided instructions from the wiki (https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Maya-Domemaster3D-Install)

We then started Maya and we found that there was no Domemaster3D shelf or menu. We are unable to find any hint in the GUI that Domemaster3D has been installed. The Applications/Domemaster3D directory was created, so we assume the problem is not related to Mac's restricted binary execution (mentioned here: https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Maya-Domemaster3D-Install#mac-os-x-108-109-and-1010-tip)

The computer is a Mac, 64-bit. Maya 2015 already had a few plugins installed, including Arnold and RenderMan. It is on a student license.

We checked to make sure the Maya.env file was installed properly, and appears to be the same as the one mentioned in the instructions.

The instructions are missing a critical piece of information in the following sentence: "When you set up a new Maya project you need to add the default supporting image files for the Domemaster3D shader." While we are then told where the images are we need to add, it doesn't tell us how. We noticed that the path to the images is placed in an environment variable in your Maya.env file, but aren't sure that's what you meant, since you seemed to be indicating that "adding" them was the user's responsibility.

**Comment by AndrewHazelden** [comment]
Hi. Do you have any custom userSetup.mel or userSetup.py scripts on your system? If any of them have syntax errors it can stop the Domemaster3D shader's startup script from running and loading the UI elements correctly.

Can you restart Maya once, and open up the Maya Script Editor window. Copy the logging messages that appear in the Script Editor window once Maya finishes loading and send me a copy of the text view email using andrew@andrewhazelden.com This will help troubleshoot the startup issues. 

Once the Domemaster3D shader is loaded in Maya and the Domemaster3D shelf and menu show up in the rendering menu set, you can use the shelf tools to easily add a fulldome or latlong camera rig to your scene that is ready to use with a single click.

**Comment by AndrewHazelden** [comment]
Hi. I have updated the **Setting up a new Maya Project** section of the Maya Tips and Tricks wiki page to help clarify your comment about "The instructions are missing a critical piece of information in the following sentence..."

https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Maya-Domemaster3D-Tips-and-Tricks#setting-up-a-new-maya-project

**Comment by uberblah** [comment]
Yes, it looks like we have about 20 additional userSetup.mel scripts sitting around, and 8 userSetup.py scripts... is it common for these scripts to interfere with one another?

**Comment by AndrewHazelden** [comment]
If there is a syntax error in one of the userSetup.py other script that runs before Domemaster3D is loaded it can stop the remaining plug-ins from starting correctly.

Can you try the following:

Open the Maya script editor window. From the History menu in the script editor window enable the "Show Stack Trace" and "Line numbers in errors" options. Then restart Maya once.

Can you attach the script editor output from the next time Maya starts. It should indicate the source of any errors that might be stopping the Domemaster3D shaders userSetup.py script from running.

Regards,
Andrew Hazelden

**Comment by uberblah** [comment]
We now have the plugin and all appropriate menus. However, when rendering from the dome stereo camera, it doesn't render as a fulldome view. It renders as a regular camera would.

OUTPUT FOLLOWS...
=========================================================
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "TURTLE" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
// Warning: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/shelf.mel line 201: The shelf "XGen" already exists.
 // 
file -f -new;
// untitled // 
commandPort -securityWarning -name commandportDefault;
updateRenderOverride;
Stereo Camera rigs:
Rig "StereoCamera": (language Python) create callback: maya.app.stereo.stereoCameraDefaultRig.createRig
A DomeStereoCamera rig has been added to the stereoRigManager.
Maya 2015.0 detected.

Stereo Camera rigs:
Rig "StereoCamera": (language Python) create callback: maya.app.stereo.stereoCameraDefaultRig.createRig
A LatLongStereoCamera rig has been added to the stereoRigManager.
Maya 2015.0 detected.

Loading the Domemaster3D menu items...
// AbcImport v1.0 using Alembic 1.5.0 (built Jul 26 2013 11:01:23)
updateRendererUI;
// AbcExport v1.0 using Alembic 1.5.0 (built Jul 26 2013 11:01:23)
// Error: file: /Applications/Autodesk/maya2015/Maya.app/Contents/scripts/startup/cutCopyPaste.mel line 97: Nothing is currently selected. //
=======================================

Plugin shows up,

**Comment by AndrewHazelden** [comment]
Hi. Just to double check you do have mental ray active as your current renderer in Maya right? I don't see any entries in your log file for the mental ray renderer loading. If you open the Hypershade and click on the mental ray "lenses" section in the Create Bar, do you see any of the Domemaster3D shaders listed?

![domemaster3d-mental-ray-nodes](https://cloud.githubusercontent.com/assets/909728/8893837/9d450f9a-3377-11e5-88f9-66df4b025578.png)

If you are using either of the Domemaster3D development shader versions for Vray or Arnold, they have to be manually installed in Maya using the resources from the folders:  

 `C:\Program Files\Domemaster3D\vray`
or 
 `C:\Program Files\Domemaster3D\arnold`

Regards,
Andrew
