### ISSUE TITLE
Repository does not include license information

### ISSUE THREAD

**Issue by en90** [zicher3d-org/domemaster-stereo-shader#5]

**Comment by AndrewHazelden** [comment]
Hi. I added a license note to the repository's main readme.md file. The shaders are distributed under a GPL v3 License which was listed in the source code and in the Domemaster3D for Maya shader's about dialog. This info was previously accessible on the side bar of Google Code where the code was originally hosted. https://code.google.com/p/domemaster-stereo-shader/
