### ISSUE TITLE
DomeViewer for 3ds max

### ISSUE THREAD

**Issue by RYG81** [zicher3d-org/domemaster-stereo-shader#6]
Hi,

Can we have DomeViewer for 3Ds max?

**Comment by AndrewHazelden** [comment]
Hi RYG81.

There are no plans at the moment to port the DomeViewer GUI to 3DS Max. However the raw OBJ format polygon geometry that is used by the Maya DomeViewer tool for displaying the imagery on each of the panoramic view projections is stored in the `C:\Program Files\Domemaster3D\sourceimages\` folder. You can import any of those OBJ meshes into your 3DS Max scene and then apply your immersive 360° imagery to the mesh and get a very similar result.

If you want a ready to go panoramic 360° media viewer that runs on Windows and supports many different view projections, I'd recommend you check out the excellent Whirligig viewer tool. It is available as a free download from:

http://www.whirligig.xyz/player2-1-2/
