### ISSUE TITLE
unable to load dynamic library 

### ISSUE THREAD

**Issue by ssseom** [zicher3d-org/domemaster-stereo-shader#7]
Hi. Thanks for share great shader.

Install Domemaster 3D Mtoa and Maya Output window shows me up

"unable to load dynamic library C:/solidangle/mtoadeploy/2015/shaders/DomemasterStereo.dll, DomemasterWxH.dll, LatLongStereo.dll".

And Maya expression window warning 

"# Warning: [mtoa] Registering UI for unknown translator "DomemasterStereo" for Maya node camera.".

I can't fix this warning, please help! sorry for bad english

**Comment by AndrewHazelden** [comment]
Hi. I don't know what exact version of Arnold MtoA you are running but one thing you might try is to follow the [Domemaster3D installation instructions](https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Arnold-MtoA-Domemaster3D-Install#windows-64-bit) here and see if this helps with the issue: Step 1. Download and install the [Visual Studio 2012 (VC++ 11.0) Redistributable Package](http://www.microsoft.com/en-us/download/details.aspx?id=30679).

**Comment by ssseom** [comment]
Thankyou Andrew. I fixed the problem. Visual Studio 2013 (VC++ 12.0) was solution.
Everything works fine at Visual Studio 2013 (VC++ 12.0).
