### ISSUE TITLE
could not create lat long shader extension

### ISSUE THREAD

**Issue by hbizira** [zicher3d-org/domemaster-stereo-shader#8]
Tried following the wiki instructions in maxwell 3.2.1.2 OSX 64 and when I run the script I get the following error:

ERROR: - Couldn't create camera lens extension :"Lat-Long Stereo", skipping... 

Could the type name have changed?

**Comment by zicher3d** [comment]
Hi Herve.

I guess you are using Maya since you are on OSX. Andrew will be able to
answer your question.

Rob

On Thu, May 12, 2016 at 4:04 PM, Herve Bizira <notifications@github.com>
wrote:

> Tried following the wiki instructions in 3.2.1.2 OSX 64 and when I run the
> script I get the following error:
>
> ERROR: - Couldn't create camera lens extension :"Lat-Long Stereo",
> skipping...
>
> Could the type name have changed?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zicher3d-org/domemaster-stereo-shader/issues/8>
>



-- 
http://www.robertoziche.com/

**Comment by AndrewHazelden** [comment]
Hi  hbizira.

At this point in time you have to have a lens shader description already attached to the camera in Maxwell before PyMaxwell (and the Automagic VR for Maxwell Render script) can adjust any of the camera lens shader properties.

To fix the error you are getting, try following Step 1 from the Automagic VR for Maxwell Render Wiki page and hopefully the problem should go away:

> ## [How do I use the script?](https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Automagic-VR-for-Maxwell-Render#how-do-i-use-the-script) ##
> 
> Step 1. Edit your Maxwell MXS scene file so there is only one camera. Set the focus distance on the camera to target the exact location in the scene that you want to use as the stereo camera rig's zero parallax distance (which is the convergence point for the left and right eyes). Then add the LatLong Stereo lens shader to the camera. 
> 

As a note, if you are interested in pipeline scripting Maxwell Render tasks you should check out the other GitHub repository called "[Maxwell Render Toolbox](https://github.com/AndrewHazelden/Maxwell-Render-Toolbox/wiki)" that I've created that takes this scripting process further.

Regards,
Andrew Hazelden
