### ISSUE TITLE
Arnold Screen Space Coordinate

### ISSUE THREAD

**Issue by ssseom** [zicher3d-org/domemaster-stereo-shader#9]
There is still swirl zone at Zenith part using Arnold Domemaster Shader.

Solution yet?

**Comment by AndrewHazelden** [comment]
Hi. Screen space mapping hasn't been enabled in the Arnold shaders yet.

The Vray for 3DS Max version of the lens shaders have implemented a new automatic stereo pole zone correction feature. When this new feature is eventually added to the Arnold shaders then the swirl zone issue will be taken care of in Arnold.

**Comment by ssseom** [comment]
Hi. Thank you for apply.

When will I use the corrected version of Arnold shaders?

When do you develop pole zone correction feature to Arnold?

Work in process?

**Comment by zicher3d** [comment]
Yes, it's a work in progress.
Arnold is a bit tricky and Andrew is trying to figure out the best way to implement those functionalities.

Let me check with him what we can do.

Rob

**Comment by AndrewHazelden** [comment]
Hi @ssseom. 

I have been fairly busy lately working on major updates to several of the other panoramic rendering tools I develop like PlayblastVR for Maya, and my Domemaster Fusion Macros toolset. That activity has been sucking up all my time during the day for the last few months so I haven't been very active on the Domemaster3D Arnold and Vray shader porting.

In the little bit of spare time I have in a day I have been working on wrapping up the development on the next Domemaster3D v2.0 release for Maya 2016.5 and 3DS Max 2017 that has several mental ray related improvements in it, and new features for the Maya Domemaster3D integration. Domemaster3D v2.0 should be complete in the next 10 days or so.

After that Domemaster3D v2.0 update is done I will look at seeing what can be done to improve the Arnold and Vray for Maya shaders to bring it into closer feature parity with the Vray for 3DS Max shader features that Roberto Ziche has added.

I have to admit that the Domemaster3D for Arnold port is a bit challenging and slow to do as their simply isn't a lot of published material out there on Arnold lens shader writing. This makes it is a slow and painful process for me with lots of trial and error to add these kind of features like screen space mapping to the lens shaders.

Cheers,
Andrew Hazelden
